language: python
python:
  - 3.6
  - nightly
script:
  - coverage run -m unittest discover # - python -m unittest discover if we don't need coverage
  - pylint --disable=R,C addme/
install:
  - pip install -r requirements.txt  # see https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py
  - pip install codecov
  - pip install coverage
  - pip install pylint
after_success:
  - codecov